name: Build and Publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  UV_SYSTEM_PYTHON: 1

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version:
            0.5.26
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Nanograd
        run: |
          uv build
          uv pip install .
      - name: Install Tools
        run: |
          uv pip install ruff
          uv pip install pytest
      - name: Lint with ruff
        run: ruff check --output-format=github ./src
      - name: Test with Pytest
        run: |
          pytest ./tests/test_nanograd
  build_wheels:
    needs:
      - test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version:
            0.5.26
      - name: Build Wheel
        run: |
          uv build --wheel
      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          name: ci-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./dist/*.whl
  build_sdist:
    name: Build source distribution
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version:
            0.5.26
      - name: Build sdist
        run: uv build --sdist
      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: ci-sdist
          path: dist/*.tar.gz
  upload_pypi:
    needs: [build_sdist, build_wheels]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: ci-*
          path: dist
          merge-multiple: true
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1



